### ISSUE TITLE
Implement PHP RFC 0001: Restructure PHP

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/php#485]
Per [PHP RFC 0001](https://github.com/paketo-buildpacks/rfcs/blob/main/text/php/0001-restructure.md) we are restructuring the PHP language family of buildpacks to make them more modular, up-to-date, and as a result, maintainable.

This issue serves as a meta-issue for tracking the implementation all of the restructure work amongst the implementation buildpacks and language family.

## Issues
- [x] https://github.com/paketo-buildpacks/php/issues/472
-----------------------
1. Deprecation warning for `buildpack.yml` usage (Parallelizable)
- [x]  https://github.com/paketo-buildpacks/php-web/issues/216
- [x] https://github.com/paketo-buildpacks/php-dist/issues/329
- [x] https://github.com/paketo-buildpacks/php-composer/issues/265
-----------------------
2. PHP Builtin Server Simple Use case
- [X] https://github.com/paketo-buildpacks/php-dist/issues/324
- [X] Waiting for release - https://github.com/paketo-buildpacks/php-builtin-server/issues/1
-----------------------
3. Implement initial php-fpm buildpack
- [X] https://github.com/paketo-buildpacks/php-fpm/issues/3
-----------------------
4. NGINX and HTTPD Web servers (parallelizable)
-  ~~paketo-buildpacks/php-httpd#2~~
- [x]  RFC for https://github.com/paketo-buildpacks/php/issues/503
- [X] https://github.com/paketo-buildpacks/php-httpd/issues/4
- [X] https://github.com/paketo-buildpacks/php-start/issues/1
- [X] ~~https://github.com/paketo-buildpacks/php/issues/479~~
- [X] paketo-buildpacks/php-nginx#2
- [X] https://github.com/paketo-buildpacks/php-start/issues/2
 These may require changes to php-dist and/or php-fpm buildpacks
-----------------------
5. Modularize composer and substitute in the language family (sequential)
- [X] paketo-buildpacks/composer#12
- [ ] In Progress - paketo-buildpacks/composer-install#4
- [X] ~~https://github.com/paketo-buildpacks/php/issues/475~~
-----------------------
6. Optional session handlers (parallelizable)
- [X] https://github.com/paketo-buildpacks/php-memcached-session-handler#1
- [X] paketo-buildpacks/php-redis-session-handler#1
-----------------------
7. Swap new buildpacks into the language family order groups, finish up
- [X] ~~https://github.com/paketo-buildpacks/php/issues/483~~
-  [x] https://github.com/paketo-buildpacks/php/issues/524
- [x] https://github.com/paketo-buildpacks/paketo-website/issues/370
-----------------------
8. Future optimizations (can be done outside of rewrite):
- [x] https://github.com/paketo-buildpacks/nginx/issues/358
- [ ] https://github.com/paketo-buildpacks/php-fpm/issues/26

**Comment by fg-j** [comment]
I'm working on https://github.com/paketo-buildpacks/php-fpm/issues/3, and I'm trying to get a handle on what functionality is required in the buildpack. Will the php-builtin-server buildpack created in https://github.com/paketo-buildpacks/php/issues/477 be responsible for generating the `php.ini` file the that the php-web buildpack [currently generates](https://github.com/paketo-buildpacks/php-web/blob/933dc22bf41db9c461e5796e0bc764f18ced92d2/features/php.go#L31-L41)? Or does the php-fpm buildpack need to generate that config file? Currently, the php-web buildpack writes the file into its layer [during every build](https://github.com/paketo-buildpacks/php-web/blob/933dc22bf41db9c461e5796e0bc764f18ced92d2/features/php.go#L23-L25)

**Comment by sophiewigmore** [comment]
@fg-j Hmm. This is a good question. Based off of my limited knowledge of PHP, I think the PHP FPM buildpack should only be responsible for configuring the `php-fpm.conf` file. I believe setting configuration in a PHP FPM config file overrides a `php.ini` file anyways. If a `php.ini` file is actually necessary to be generated, my instinct would be to have the php-builtin-server buildpack handle this, since the php-httpd and php-nginx counterparts generate their respective config files as well. This also  makes more sense to me since the php-fpm buildpack is an optional buildpack in this order grouping.

Happy for @paketo-buildpacks/php-maintainers to weigh in as well

**Comment by dmikusa-pivotal** [comment]
My $0.02. I would suggest that we have the buildpack which installs PHP add a default php.ini file. This is traditionally how it's done. When you install PHP with `apt` or another package manager, that provides a default `php.ini`. It should also set `PHPRC` and `PHP_INI_SCAN_DIR`.

The individual buildpacks can then customize that by adding php.ini snippets to the `PHP_INI_SCAN_DIR`. Right now, that points to something in the application workspace. That is probably OK, we just have to regenerate those every time the buildpack runs. Alternatively, we could have a second buildpack-only location for that. You can add multiple folders to the scan dir.

>It is possible to scan multiple directories by separating them with the platform-specific path separator (; on Windows, NetWare and RISC OS; : on all other platforms; the value PHP is using is available as the PATH_SEPARATOR constant).

**Comment by fg-j** [comment]
In that case, I think https://github.com/paketo-buildpacks/php-dist/issues/324 needs to be updated to include generating a default configuration file (and possibly setting up the `PHP_INI_DIR`).

**Comment by arjun024** [comment]
@fg-j 
This addressed directly in the rfc.

> * **php-dist**:
  Installs the [`php`](https://www.php.net) distribution, making it available on the `$PATH`
>   * provides: `php`
>   * requires: none
>
>  This distribution must include popular modules like memcached, mongodb,
 > mysqli, openssl, phpiredis, zlib etc; and a suitable `php.ini`.

**Comment by ForestEckhardt** [comment]
@sophiewigmore Is this issue still being used to track work or are we done?

**Comment by sophiewigmore** [comment]
@ForestEckhardt as you can see, the documentation issue is still in review. That's the last remaining issue. I will close out this issue when that is available on the Paketo website.
